MALE = 'Male'
FEMALE = 'Female'

SEX_CHOICES = (
    (MALE, MALE),
    (FEMALE, FEMALE),
)

AU_NSW = 'NSW'
AU_VIC = 'VIC'
AU_QLD = 'QLD'
AU_TAS = 'TAS'
AU_WA = 'WA'
AU_ACT = 'ACT'
AU_NT = 'NT'

AU_STATE_CHOICES = (
    (AU_NSW, AU_NSW),
    (AU_VIC, AU_VIC),
    (AU_QLD, AU_QLD),
    (AU_TAS, AU_TAS),
    (AU_WA, AU_WA),
    (AU_ACT, AU_ACT),
    (AU_NT, AU_NT),
)

AU_SYDNEY = 'Sydney'
AU_MELBOURNE = 'Melbourne'
AU_ADELAIDE = 'Adelaide'
AU_HOBART = 'Hobart'
AU_PERTH = 'Perth'
AU_DARWIN = 'Darwin'
AU_CANBERRA = 'Canberra'

AU_CITY_CHOICES = (
    (AU_SYDNEY, AU_SYDNEY),
    (AU_MELBOURNE, AU_MELBOURNE),
    (AU_ADELAIDE, AU_ADELAIDE),
    (AU_HOBART, AU_HOBART),
    (AU_HOBART, AU_HOBART),
    (AU_DARWIN, AU_DARWIN),
    (AU_CANBERRA, AU_CANBERRA),
)
